name: Update recent activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@v0.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: ybg345
          MAX_LINES: 5
          COMMIT_MSG: "chore: update recent GitHub activity"
